### ISSUE TITLE
update to 0.13.3

### ISSUE THREAD

**Issue by djindjic** [cconstantin/angular-ui-bootstrap-rails#20]
Could you please update ui-bootstrap to 0.13.3? I have some date picker issues resolved with new version.

**Comment by cconstantin** [comment]
@djindjic I won't have the time to update this week, but I could merge a PR if you need it soon.

**Comment by djindjic** [comment]
ok, I've made it [here](https://github.com/cconstantin/angular-ui-bootstrap-rails/pull/21)

**Comment by cconstantin** [comment]
Thanks @djindjic, PR merged, gem published.
