### ISSUE TITLE
Failed to load template

### ISSUE THREAD

**Issue by xskif** [cconstantin/angular-ui-bootstrap-rails#23]
Hello!

Should i add templates of the "angular-ui" manually?

**Comment by cconstantin** [comment]
See the readme. Use `//= require angular-ui-bootstrap-tpls` to include the default templates.

**Comment by grauschnabel** [comment]
What is the 'standard' way to modify this templates?

**Comment by cconstantin** [comment]
@grauschnabel see http://stackoverflow.com/questions/17660947/can-you-override-specific-templates-in-angularui-bootstrap
