### ISSUE TITLE
Major updates

### ISSUE THREAD

**Issue by d-ash** [cconstantin/angular-ui-bootstrap-rails#24]
A month ago there were major changes in angular-ui-bootstrap. Particularly they've replaced and deprecated some directives without 'uib-' prefix (e.g. alert, progressBar, accordion).

It's already causes some confusion: https://github.com/angular-ui/bootstrap/issues/4687

**Comment by cconstantin** [comment]
@d-ash any chance you can submit a PR?

**Comment by d-ash** [comment]
@cconstantin Submitted

**Comment by cconstantin** [comment]
Thanks @d-ash, gem published.
